### ISSUE TITLE
edit entity name

### ISSUE THREAD

**Issue by rrgks6221** [GardenOfWriter/garden-of-writer-backend#15]
## Summary

entity option 의 entity name 을 추가한다.

## description

#8 에서 entity class 에 entity 를 붙여줬지만 table name 을 적용하지 않아서 실제 db table 도 entity suffix 가 붙었기 때문에 table name 속성을 추가해준다.

## To-Do

- [x] 각 entitiy class decorator 에 name option 추가
- [x] many-to-many 데코레이터 제거
- [x] base entity 만들어 상속받아 사용

## Reference Link

> 참고한 레퍼런스 (선택)

## Related Link

#8
